
apiVersion: apps/v1
kind: Deployment
metadata: { name: facturacion-ecuador }
spec:
  replicas: 2
  selector: { matchLabels: { app: facturacion-ecuador } }
  template:
    metadata: { labels: { app: facturacion-ecuador } }
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports: [{containerPort: 8080}]
          env:
            - name: APP_DB_URL
              valueFrom: { secretKeyRef: { name: facturacion-secrets, key: APP_DB_URL } }
            - name: APP_DB_USER
              valueFrom: { secretKeyRef: { name: facturacion-secrets, key: APP_DB_USER } }
            - name: APP_DB_PASS
              valueFrom: { secretKeyRef: { name: facturacion-secrets, key: APP_DB_PASS } }
---
apiVersion: v1
kind: Service
metadata: { name: facturacion-ecuador }
spec:
  selector: { app: facturacion-ecuador }
  ports: [{ name: http, port: {{ .Values.service.port }}, targetPort: 8080 }]
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: facturacion-ecuador
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls: [{ hosts: ["{{ .Values.ingress.host }}"], secretName: "{{ .Values.ingress.tlsSecret }}" }]
  rules:
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: facturacion-ecuador
                port: { number: {{ .Values.service.port }} }
