ALTER TABLE IF EXISTS edoc ADD COLUMN IF NOT EXISTS tipo text;
ALTER TABLE IF EXISTS edoc ADD COLUMN IF NOT EXISTS clave_acceso text;
ALTER TABLE IF EXISTS edoc ADD COLUMN IF NOT EXISTS numero_autorizacion text;
ALTER TABLE IF EXISTS edoc ADD COLUMN IF NOT EXISTS fecha_autorizacion timestamptz;
ALTER TABLE IF EXISTS edoc ADD COLUMN IF NOT EXISTS xml_path text;
ALTER TABLE IF EXISTS edoc ADD COLUMN IF NOT EXISTS pdf_path text;
ALTER TABLE IF EXISTS edoc ADD COLUMN IF NOT EXISTS estado text;
