
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: facturacion-allow-monitoring
spec:
  podSelector:
    matchLabels:
      app: facturacion-backend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - {}
  egress:
  - {}
