
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: facturacion-ecuador
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts: [ "fe.example.com" ]
      secretName: fe-tls
  rules:
    - host: fe.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: facturacion-ecuador
                port:
                  number: 80
